ALTER TABLE messages
    ADD COLUMN edited_at DATETIME(6) NULL DEFAULT NULL AFTER content,
    ADD COLUMN deleted_at DATETIME(6) NULL DEFAULT NULL AFTER edited_at,
    ADD COLUMN updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) AFTER is_read;
